// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	_ govalid.Validator = (*PatternPhone)(nil)

	// ErrNilPatternPhone is returned when the PatternPhone is nil.
	ErrNilPatternPhone = errors.New("input PatternPhone is nil")

	// ErrPatternPhonePhonePatternValidation is returned when the field does not match pattern ^[0-9]{3}-[0-9]{3}-[0-9]{4}$.
	ErrPatternPhonePhonePatternValidation = govaliderrors.ValidationError{Reason: "field Phone must match pattern ^[0-9]{3}-[0-9]{3}-[0-9]{4}$", Path: "PatternPhone.Phone", Type: "pattern"}
)

func ValidatePatternPhoneContext(ctx context.Context, t *PatternPhone) error {
	if t == nil {
		return ErrNilPatternPhone
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.MatchPattern("^[0-9]{3}-[0-9]{3}-[0-9]{4}$", t.Phone) {
		err := ErrPatternPhonePhonePatternValidation
		err.Value = t.Phone
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidatePatternPhone(t *PatternPhone) error {
	return ValidatePatternPhoneContext(context.Background(), t)
}

func (t *PatternPhone) Validate() error {
	return ValidatePatternPhone(t)
}

func (t *PatternPhone) ValidateContext(ctx context.Context) error {
	return ValidatePatternPhoneContext(ctx, t)
}
