// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	_ govalid.Validator = (*PatternCode)(nil)

	// ErrNilPatternCode is returned when the PatternCode is nil.
	ErrNilPatternCode = errors.New("input PatternCode is nil")

	// ErrPatternCodeCodePatternValidation is returned when the field does not match pattern ^[A-Z]{2}[0-9]{4}$.
	ErrPatternCodeCodePatternValidation = govaliderrors.ValidationError{Reason: "field Code must match pattern ^[A-Z]{2}[0-9]{4}$", Path: "PatternCode.Code", Type: "pattern"}
)

func ValidatePatternCodeContext(ctx context.Context, t *PatternCode) error {
	if t == nil {
		return ErrNilPatternCode
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.MatchPattern("^[A-Z]{2}[0-9]{4}$", t.Code) {
		err := ErrPatternCodeCodePatternValidation
		err.Value = t.Code
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidatePatternCode(t *PatternCode) error {
	return ValidatePatternCodeContext(context.Background(), t)
}

func (t *PatternCode) Validate() error {
	return ValidatePatternCode(t)
}

func (t *PatternCode) ValidateContext(ctx context.Context) error {
	return ValidatePatternCodeContext(ctx, t)
}
