// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	_ govalid.Validator = (*PatternCSV)(nil)

	// ErrNilPatternCSV is returned when the PatternCSV is nil.
	ErrNilPatternCSV = errors.New("input PatternCSV is nil")

	// ErrPatternCSVTagsPatternValidation is returned when the field does not match pattern ^[a-z]+(,[a-z]+)*$.
	ErrPatternCSVTagsPatternValidation = govaliderrors.ValidationError{Reason: "field Tags must match pattern ^[a-z]+(,[a-z]+)*$", Path: "PatternCSV.Tags", Type: "pattern"}
)

func ValidatePatternCSVContext(ctx context.Context, t *PatternCSV) error {
	if t == nil {
		return ErrNilPatternCSV
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.MatchPattern("^[a-z]+(,[a-z]+)*$", t.Tags) {
		err := ErrPatternCSVTagsPatternValidation
		err.Value = t.Tags
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidatePatternCSV(t *PatternCSV) error {
	return ValidatePatternCSVContext(context.Background(), t)
}

func (t *PatternCSV) Validate() error {
	return ValidatePatternCSV(t)
}

func (t *PatternCSV) ValidateContext(ctx context.Context) error {
	return ValidatePatternCSVContext(ctx, t)
}
