// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	_ govalid.Validator = (*Pattern)(nil)

	// ErrNilPattern is returned when the Pattern is nil.
	ErrNilPattern = errors.New("input Pattern is nil")

	// ErrPatternUsernamePatternValidation is returned when the field does not match pattern ^[a-z]+$.
	ErrPatternUsernamePatternValidation = govaliderrors.ValidationError{Reason: "field Username must match pattern ^[a-z]+$", Path: "Pattern.Username", Type: "pattern"}
)

func ValidatePatternContext(ctx context.Context, t *Pattern) error {
	if t == nil {
		return ErrNilPattern
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.MatchPattern("^[a-z]+$", t.Username) {
		err := ErrPatternUsernamePatternValidation
		err.Value = t.Username
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidatePattern(t *Pattern) error {
	return ValidatePatternContext(context.Background(), t)
}

func (t *Pattern) Validate() error {
	return ValidatePattern(t)
}

func (t *Pattern) ValidateContext(ctx context.Context) error {
	return ValidatePatternContext(ctx, t)
}
