// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// PatternInitializer implements ValidatorInitializer for the pattern validator.
type PatternInitializer struct{}

// Marker returns the marker identifier for the pattern validator.
func (p PatternInitializer) Marker() string {
	return markers.GoValidMarkerPattern
}

// Init initializes the pattern validator factory.
func (p PatternInitializer) Init() registry.ValidatorFactory {
	return rules.ValidatePattern
}
